import math

# game settings
RES = WIDTH, HEIGHT = 1000, 900
FPS = 60
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2


# Player settings
# PLAYER_POS = 1.5, 5
# PLAYER_ANGLE = 60
# PLAYER_SPEED = 0.004
# PLAYER_ROT_SPEED = 0.002
# PLAYER_SIZE_SCALE = 60
# PLAYER_MAX_HEALTH = 100


# AGENT SETTINGS
PLAYER_POS = 3.5, 6
PLAYER_ANGLE = 60
PLAYER_SPEED = 0.005
PLAYER_ROT_SPEED = 0.003
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100



MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS


TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2



# AGENT SETTINGS
MAX_MEMORY = 100_000
BATCH_SIZE = 256
LR = 0.01


# SCORE SETTINGS
SCORE_PER_ENEMY = 100
HEALTH_BONUS = 10
TIME_PENALTY = -0.1
SCORE_PER_AREA = 10
HEALTH_THRESHOLD = 50
